name: Deploy Website
on:
  push:
    branches:
      - main

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build website
        run: yarn build
      - name: Deploy to Cloudflare Pages
        run: yarn deploy:pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.__CLOUDFLARE_API_TOKEN_SECRET__ }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.__CLOUDFLARE_ACCOUNT_ID_VAR__ }}
